---

- name: Install software-properties-common
  apt:
    pkg:
      - software-properties-common
    state: latest
    update_cache: yes
  become: yes

- name: Add universe repo
  apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu bionic universe"
    state: present
    filename: universe
  become: yes

- name: Add certbot repo
  apt_repository:
    repo: "ppa:certbot/certbot"
    state: present
  become: yes

- name: Install certbot
  apt:
    pkg:
      - certbot
      - python-certbot-nginx
    state: latest
    update_cache: yes
  become: yes
